#!/bin/bash
#
# ~/ANSI_escape_colors
#
#  Code sequences of ANSI escape colors

######################################################################
#                                                                    #
# Modification History                                               #
#  2021-12-03   Ricardo A.O. Medina   borrowed from internet         #
#                                                                    #
# Source                                                             #
# https://stackoverflow.com/questions/4842424/list-of-ansi-color-escape-sequences 
#                                                                    #
# Created with Bash version                                          #
#  5.0.18(1)-release                                                 #
#                                                                    #
######################################################################

## set ANSI escape colors

Black='\033[0;30m'
Dark_Gray='\033[1;30m'
Red='\033[0;31m'
Light_Red='\033[1;31m'
Green='\033[0;32m'
Light_Green='\033[1;32m'
Brown_Orange='\033[0;33m'
Yellow='\033[1;33m'
Blue='\033[0;34m'
Light_Blue='\033[1;34m'
Purple='\033[0;35m'
Light_Purple='\033[1;35m'
Cyan='\033[0;36m'
Light_Cyan='\033[1;36m'
Light_Gray='\033[0;37m'
White='\033[1;37m'
NC='\033[0m' # No Color


# emacs:
# Local Variables:
# sh-basic-offset: 2
# End:
